name: "Hello World"
description: "Greet someone and record the time"
inputs:
  GITHUB_TOKEN: # id of input
    description: "Token"
    required: true
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: "dist/index.js"
