on:
  - push

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: albinaxtelius/actions-testing@v1.2-beta.2
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
